version: '3.8'
services:
  boxViz:
    build: .
    container_name: ${USER}_boxViz
    ipc: host
    network: host
    privileged: true
    volumes:
      - /persist/${USER}:/persist/${USER}
      - /root/.ssh:/root/.ssh
      - /home/${USER}:/home/${USER}
    