version: '3.8'
services:
  imageviewer:
    build: .
    restart: on-failure
    ports:
      - 5000:5000/tcp
    volumes:
      - /persist/${USER}:/persist/${USER}
      - /persist/${USER}/.aws:/root/.aws
      - /root/.ssh:/root/.ssh
      - /home/${USER}:/home/${USER}
    